<?php

/*
 * carina erp v.1.03b
 * kardesyazilim.net istanbulmobile.net
 * Kardeş Yazılım ve Bilişim Hizmetleri
 * labs@kardesyazilim.net
 * labs.kardesyazilim.net
 * Oct 7, 2013 - 2:33:44 AM  / file name: [db] (db.inc)
 * UTF-8 - markado - default
 * help doc : db - (db.inc)
 */



//db type
//!important user db permission check 
//cluster
$db_type ="mysql";

$dbsrv ="localhost";


$mdb = "carina_master";
$sdb = "carina_slave";
$xdb = "carina_2013"; //create script

$dbusr="carina";
$dbpass="qweytr";
$dbencode = "utf-8";






?>
