<?php

/*
 * carina erp v.1.03b
 * kardesyazilim.net istanbulmobile.net
 * Kardeş Yazılım ve Bilişim Hizmetleri
 * labs@kardesyazilim.net
 * labs.kardesyazilim.net
 * Oct 7, 2013 - 11:46:38 PM  / file name: [render] (render.inc)
 * UTF-8 - markado - default
 * help doc : render - (render.inc)
 */

class cRender{
    
    function __construct() {
        //html templare render
        echo 'test';
    }
}
?>
